export const EVENTS = Object.freeze({
  JOIN_ROOM: "JOIN-ROOM",
  LEAVE_ROOM: "LEAVE-ROOM",

  SEND_CHANGES: "SEND-CHANGES",
  RECEIVE_CHANGES: "RECEIVE-CHANGES",

  CURSOR_MOVEMENT:"CURSOR-MOVEMENT",
  REVEIVE_CURSOR_MOVEMENT:"RECEIVE-CURSOR-MOVEMENT"
});
